# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-11-03 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 3, 11, 0, 16, 913674)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
